# Generated by Django 4.1.4 on 2023-04-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0006_alter_perpage_options_alter_perpage_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perpage',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
