# Generated by Django 4.1.4 on 2023-04-07 01:45

import User_Profile.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_Profile', '0007_perpage_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perpage',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelManagers(
            name='perpage',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='password',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='perpage',
            name='username',
        ),
        migrations.AddField(
            model_name='perpage',
            name='id_t',
            field=models.CharField(blank=True, default=User_Profile.utils.generate_code, max_length=12),
        ),
        migrations.AddField(
            model_name='perpage',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
